# # Starter pipeline
# - task: FlutterInstall@0
#   inputs:
#     channel: 'stable'
#     version: 'latest'
# # Start with a minimal pipeline that you can customize to build and deploy your code.
# - task: FlutterBuild@0
#   inputs:
#     target: 'apk'
#     projectDirectory: '$(projectDirectory)'
#     apkTargetPlatform: 'android-arm64'

jobs:
  - job: Android
    pool:
      vmImage: 'macOS-10.13'
    steps:
    - task: FlutterInstall@0
    - task: FlutterBuild@0
      inputs:
        target: apk
        projectDirectory: $(projectDirectory)
    - task: CopyFiles@2
      inputs:
        contents: '**/*.apk'
        targetFolder: '$(build.artifactStagingDirectory)'

# trigger:
# - master

# pool:
#   vmImage: 'ubuntu-latest'

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
