variables:
  projectDirectory: testapp
jobs:
  - job: Flutter
    pool:
      vmImage: 'macOS-10.13'
    steps:
    - task: InstallAppleProvisioningProfile@1
      inputs:
        provisioningProfileLocation: 'secureFiles'
        provProfileSecureFile: 'a5f1790c-ddb5-4105-ac1f-5bfca611295d.mobileprovision'
    - task: InstallAppleCertificate@2
      inputs:
        certSecureFile: 'cert_iphone_luxoft.p12'
        certPwd: '12345'
        keychain: 'temp'
    - task: FlutterInstall@0
    - task: FlutterBuild@0
      inputs:
        target: all
        projectDirectory: ./