variables:
  projectDirectory: testapp
jobs:
  - job: Android
    pool:
      vmImage: 'macOS-10.13'
    steps:
    - task: FlutterInstall@0
    - task: FlutterBuild@0
      inputs:
        target: all
        projectDirectory: ./
    - task: CopyFiles@2
      inputs:
        contents: '**/*.apk'
        targetFolder: '$(build.artifactStagingDirectory)'